// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/subscriptions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Получить список подписок",
                "parameters": [
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "вернуть записи следующие за after_id",
                        "name": "after_id",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1000,
                        "description": "вернуть не более limit записей",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "x-example": "60601fee-2bf1-4721-ae6f-7636e79a0cba",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "minLength": 1,
                        "type": "string",
                        "x-example": "Yandex Plus",
                        "description": "Service Name",
                        "name": "service_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "01-0001",
                        "description": "From Date",
                        "name": "from_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "12-9999",
                        "description": "To Date",
                        "name": "to_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Subscription"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            },
            "post": {
                "description": "` + "`" + `end_date` + "`" + ` - опциональное поле. Если не указано или передано как null,\nподписка считается бессрочной (внутренне используется 12-9999)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Создать подписку",
                "parameters": [
                    {
                        "description": "CreateSubscriptionRequest",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Subscription"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/subscriptions/total": {
            "get": {
                "description": "Подсчет стоимости подписок за указанный период.\nЕсли ` + "`" + `to_date` + "`" + ` не указан, используется текущий месяц.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Подсчет суммарной стоимости подписок",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "x-example": "60601fee-2bf1-4721-ae6f-7636e79a0cba",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "minLength": 1,
                        "type": "string",
                        "x-example": "Yandex Plus",
                        "description": "Service Name",
                        "name": "service_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "01-0001",
                        "x-example": "07-2025",
                        "description": "From Date",
                        "name": "from_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "x-example": "08-2025",
                        "description": "To Date",
                        "name": "to_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TotalCostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/subscriptions/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Получить подписку",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "x-example": "42",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Subscription"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "Идемпотентен. Успех говорит, что подписка или была удалена или отсутствует.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Удалить подписку",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "x-example": "42",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            },
            "patch": {
                "description": "Обновляет только переданные поля. ` + "`" + `user_id` + "`" + ` не может быть изменен.\nПоле ` + "`" + `updated` + "`" + ` обязательное, должно иметь значение из предыдущего GET-запроса.\nВ случае, если переданное значение ` + "`" + `updated` + "`" + ` не совпадает с текущим в БД, возвращается 409 (Conflict) с актуальной версией записи.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Обновить подписку",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "x-example": "42",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UpdateSubscriptionRequest",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Subscription"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ConflictResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ConflictResponse": {
            "type": "object",
            "properties": {
                "current": {
                    "$ref": "#/definitions/model.Subscription"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.CreateSubscriptionRequest": {
            "type": "object",
            "required": [
                "service_name",
                "start_date",
                "user_id"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "default": "12-9999",
                    "example": "12-2025"
                },
                "price": {
                    "type": "integer",
                    "default": 0,
                    "minimum": 0,
                    "example": 400
                },
                "service_name": {
                    "type": "string",
                    "example": "Yandex Plus"
                },
                "start_date": {
                    "type": "string",
                    "example": "07-2025"
                },
                "user_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "60601fee-2bf1-4721-ae6f-7636e79a0cba"
                }
            }
        },
        "api.UpdateSubscriptionRequest": {
            "type": "object",
            "required": [
                "updated"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "12-2025"
                },
                "price": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 100
                },
                "service_name": {
                    "type": "string",
                    "example": "Yandex Plus"
                },
                "start_date": {
                    "type": "string",
                    "example": "07-2025"
                },
                "updated": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-07-01T14:38:00.000Z"
                }
            }
        },
        "model.Subscription": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-07-01T14:38:00.000Z"
                },
                "deleted": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-12-01T14:38:00.000Z"
                },
                "end_date": {
                    "type": "string",
                    "example": "12-2025"
                },
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string",
                    "example": "07-2025"
                },
                "updated": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-07-01T14:38:00.000Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "60601fee-2bf1-4721-ae6f-7636e79a0cba"
                }
            }
        },
        "model.TotalCostResponse": {
            "type": "object",
            "properties": {
                "total_cost": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Сервис агрегации данных об онлайн подписках пользователей",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
