basePath: /api
definitions:
  api.CreateSubscriptionRequest:
    properties:
      end_date:
        example: 12-2025
        type: string
      price:
        default: 0
        minimum: 0
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        format: uuid
        type: string
    required:
    - service_name
    - start_date
    - user_id
    type: object
  api.UpdateSubscriptionRequest:
    properties:
      end_date:
        example: 12-2025
        type: string
      price:
        minimum: 400
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      updated:
        example: "2025-07-01T14:38:00.000Z"
        format: date-time
        type: string
    type: object
  model.Subscription:
    properties:
      created:
        example: "2025-07-01T14:38:00.000Z"
        format: date-time
        type: string
      end_date:
        example: 12-2025
        type: string
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        example: 07-2025
        type: string
      updated:
        example: "2025-07-01T14:38:00.000Z"
        format: date-time
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  model.TotalCostResponse:
    properties:
      total_cost:
        type: integer
    type: object
info:
  contact: {}
  license:
    name: Apache 2.0
  title: Сервис агрегации данных об онлайн подписках пользователей
  version: "1.0"
paths:
  /subscriptions:
    get:
      parameters:
      - default: 0
        description: вернуть записи следующие за after_id
        in: query
        minimum: 0
        name: after_id
        type: integer
      - default: 1
        description: вернуть не более limit записей
        in: query
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Subscription'
            type: array
        "400":
          description: Bad Request
        "409":
          description: Conflict
      summary: Получить список подписок
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      parameters:
      - description: CreateSubscriptionRequest
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/api.CreateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Subscription'
        "400":
          description: Bad Request
        "409":
          description: Conflict
      summary: Создать подписку
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      description: Идемпотентен. Успех говорит, что подписка или была удалена или
        отсутсвует.
      parameters:
      - description: Subscription ID
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
        x-example: "42"
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Удалить подписку
      tags:
      - subscriptions
    get:
      parameters:
      - description: Subscription ID
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
        x-example: "42"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subscription'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "409":
          description: Conflict
      summary: Получить подписку
      tags:
      - subscriptions
    patch:
      consumes:
      - application/json
      parameters:
      - description: Subscription ID
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
        x-example: "42"
      - description: UpdateSubscriptionRequest
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/api.UpdateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subscription'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.Subscription'
      summary: Обновить подписку
      tags:
      - subscriptions
  /subscriptions/total:
    get:
      parameters:
      - description: User ID
        format: uuid
        in: query
        name: user_id
        required: true
        type: string
        x-example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
      - description: Service Name
        in: query
        minLength: 1
        name: service_name
        type: string
        x-example: Yandex Plus
      - description: From Date
        format: date
        in: query
        name: from_date
        type: string
        x-example: "2025-07-04"
      - description: To Date
        format: date
        in: query
        name: to_date
        type: string
        x-example: "2025-08-25"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TotalCostResponse'
        "400":
          description: Bad Request
      summary: Подсчет суммарной стоимости подписок
      tags:
      - subscriptions
swagger: "2.0"
