# Not used now!
# Instead DB_PASSWORD is generated on the fly. See Makefile#env-init

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_PASSWORD: "your strong password"
