apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ${SERVER_IMG}
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_ADDR
          value: ":8080"      # сообщаем приложению на каком порту оно работает
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
        - name: DB_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_ADDR
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        # Опционально: readinessProbe для сервера, если есть /health